baseurl = "http://liply.net" # Hostname (and path) to the root.
title = "liply.net" # Site title.
theme = "coder" # Set the theme.
languagecode = "ja" # The site’s language code.

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

disqusShortname = "yourdiscussshortname" # Enable or disable Disqus

[params] # theme parameters
    author = "liply" # Author's name.
    info = "frontend programmer" # Author's job title or info.
    description = "liply.net" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
#    avatarurl = "images/avatar.jpg" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "where there's a will, there's a way." # Add footer content

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # RTL support
    rtl = false

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/liply/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/liplynet/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"